steps:
  # 1. Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/scenic-parity-465008-n7/containers/excuse-ai-service:$BUILD_ID'
      - '.'

  # 2. Artifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/scenic-parity-465008-n7/containers/excuse-ai-service:$BUILD_ID'

  # 3. Cloud Runにデプロイ（認証情報の衝突を回避）
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'excuse-ai-service'
      - '--image=asia-northeast1-docker.pkg.dev/scenic-parity-465008-n7/containers/excuse-ai-service:$BUILD_ID'
      - '--region=asia-northeast1'
      - '--allow-unauthenticated'
      - '--set-env-vars=PROJECT_ID=scenic-parity-465008-n7,LOCATION=asia-northeast1,VERTEX_AI_LOCATION=us-central1'
      - '--min-instances=0' 
      - '--memory=512Mi'
      - '--timeout=300'
      # ⬇️ 実行コンテナが使用するSAを指定（これは必須）
      - '--service-account=excuse-ai-sa@scenic-parity-465008-n7.iam.gserviceaccount.com' 
      # ⬇️ デプロイの実行主体としてCloud Build SAを強制的に指定 (認証衝突回避)
      - '--impersonate-service-account=870325242719@cloudbuild.gserviceaccount.com'
  
  # 4. デプロイ結果表示
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'describe'
      - 'excuse-ai-service'
      - '--region=asia-northeast1'
      - '--format=value(status.url)'

# ビルド設定
options:
  logging: CLOUD_LOGGING_ONLY